api_name: []
items:
- _type: class
  children: []
  class: azure.mgmt.network.models.ApplicationGatewaySslProtocol
  fullName: azure.mgmt.network.models.ApplicationGatewaySslProtocol
  inheritance:
  - enum.Enum
  - builtins.object
  module: azure.mgmt.network.models
  name: ApplicationGatewaySslProtocol
  source:
    id: ApplicationGatewaySslProtocol
    path: Users/eric/.virtualenvs/sphinx-docfx-yaml/lib/python3.5/site-packages/azure/mgmt/network/models/network_management_client_enums.py
    remote:
      branch: master
      path: Users/eric/.virtualenvs/sphinx-docfx-yaml/lib/python3.5/site-packages/azure/mgmt/network/models/network_management_client_enums.py
      repo: git@github.com:ericholscher/azure-sdk-for-python.git
    startLine: 27
  summary: An enumeration.
  type: Class
  uid: azure.mgmt.network.models.ApplicationGatewaySslProtocol
