api_name: []
items:
- _type: class
  children: []
  class: azure.mgmt.compute.models.WinRMConfiguration
  fullName: azure.mgmt.compute.models.WinRMConfiguration
  inheritance:
  - msrest.serialization.Model
  - builtins.object
  module: azure.mgmt.compute.models
  name: WinRMConfiguration
  source:
    id: WinRMConfiguration
    path: Users/eric/.virtualenvs/sphinx-docfx-yaml/lib/python3.5/site-packages/azure/mgmt/compute/models/win_rm_configuration.py
    remote:
      branch: master
      path: Users/eric/.virtualenvs/sphinx-docfx-yaml/lib/python3.5/site-packages/azure/mgmt/compute/models/win_rm_configuration.py
      repo: https://github.com/Azure/azure-sdk-for-python/
    startLine: 15
  summary: "Describes Windows Remote Management configuration of the VM.\n\n:param\
    \ listeners: the list of Windows Remote Management listeners\n:type listeners:\
    \ list of :class:`WinRMListener\n <azure.mgmt.compute.models.WinRMListener>`"
  type: Class
  uid: azure.mgmt.compute.models.WinRMConfiguration
