api_name: []
items:
- _type: class
  children: []
  class: azure.mgmt.network.models.ApplicationGatewayBackendAddress
  fullName: azure.mgmt.network.models.ApplicationGatewayBackendAddress
  inheritance:
  - msrest.serialization.Model
  - builtins.object
  module: azure.mgmt.network.models
  name: ApplicationGatewayBackendAddress
  source:
    id: ApplicationGatewayBackendAddress
    path: Users/eric/.virtualenvs/sphinx-docfx-yaml/lib/python3.5/site-packages/azure/mgmt/network/models/application_gateway_backend_address.py
    remote:
      branch: master
      path: Users/eric/.virtualenvs/sphinx-docfx-yaml/lib/python3.5/site-packages/azure/mgmt/network/models/application_gateway_backend_address.py
      repo: https://github.com/Azure/azure-sdk-for-python/
    startLine: 15
  summary: 'Backend Address of application gateway.


    :param fqdn: Dns name

    :type fqdn: str

    :param ip_address: Ip address

    :type ip_address: str'
  type: Class
  uid: azure.mgmt.network.models.ApplicationGatewayBackendAddress
