api_name: []
items:
- _type: class
  children: []
  class: azure.mgmt.web.models.ManagedHostingEnvironment
  fullName: azure.mgmt.web.models.ManagedHostingEnvironment
  inheritance:
  - azure.mgmt.web.models.resource.Resource
  - msrest.serialization.Model
  - builtins.object
  module: azure.mgmt.web.models
  name: ManagedHostingEnvironment
  source:
    id: ManagedHostingEnvironment
    path: azure-mgmt-web/azure/mgmt/web/models/managed_hosting_environment.py
    remote:
      branch: master
      path: azure-mgmt-web/azure/mgmt/web/models/managed_hosting_environment.py
      repo: https://github.com/Azure/azure-sdk-for-python/
    startLine: 15
  summary: "Description of a managed hosting environment.\n\n:param id: Resource Id\n\
    :type id: str\n:param name: Resource Name\n:type name: str\n:param kind: Kind\
    \ of resource\n:type kind: str\n:param location: Resource Location\n:type location:\
    \ str\n:param type: Resource type\n:type type: str\n:param tags: Resource tags\n\
    :type tags: dict\n:param managed_hosting_environment_name: Name of the managed\
    \ hosting\n environment\n:type managed_hosting_environment_name: str\n:param managed_hosting_environment_location:\
    \ Location of the managed\n hosting environment e.g. \"West US\"\n:type managed_hosting_environment_location:\
    \ str\n:param status: Current status of the managed hosting environment.\n Possible\
    \ values include: 'Preparing', 'Ready', 'Deleting'\n:type status: str or :class:`ManagedHostingEnvironmentStatus\n\
    \ <azure.mgmt.web.models.ManagedHostingEnvironmentStatus>`\n:param virtual_network:\
    \ Description of the managed hosting environment's\n virtual network\n:type virtual_network:\
    \ :class:`VirtualNetworkProfile\n <azure.mgmt.web.models.VirtualNetworkProfile>`\n\
    :param ipssl_address_count: Number of ip ssl addresses reserved for the\n managed\
    \ hosting environment\n:type ipssl_address_count: int\n:param dns_suffix: DNS\
    \ suffix of the managed hosting environment\n:type dns_suffix: str\n:param subscription_id:\
    \ Subscription of the managed hosting environment\n (read only)\n:type subscription_id:\
    \ str\n:param resource_group: Resource group of the managed hosting environment\n\
    \ (read only)\n:type resource_group: str\n:param environment_is_healthy: True/false\
    \ indicating whether the managed\n hosting environment is healthy\n:type environment_is_healthy:\
    \ bool\n:param environment_status: Detailed message about with results of the\n\
    \ last check of the managed hosting environment\n:type environment_status: str\n\
    :param suspended: True/false indicating whether the managed hosting\n environment\
    \ is suspended. The environment can be suspended e.g. when the\n management endpoint\
    \ is no longer available\n (most likely because NSG blocked the incoming traffic)\n\
    :type suspended: bool\n:param api_management_account: Resource id of the api management\
    \ account\n associated with this managed hosting environment (read only)\n:type\
    \ api_management_account: str"
  type: Class
  uid: azure.mgmt.web.models.ManagedHostingEnvironment
