api_name: []
items:
- _type: class
  children: []
  class: azure.mgmt.monitor.models.ServiceDiagnosticSettings
  fullName: azure.mgmt.monitor.models.ServiceDiagnosticSettings
  inheritance:
  - msrest.serialization.Model
  - builtins.object
  module: azure.mgmt.monitor.models
  name: ServiceDiagnosticSettings
  source:
    id: ServiceDiagnosticSettings
    path: azure-mgmt-monitor/azure/mgmt/monitor/models/service_diagnostic_settings.py
    remote:
      branch: master
      path: azure-mgmt-monitor/azure/mgmt/monitor/models/service_diagnostic_settings.py
      repo: https://github.com/Azure/azure-sdk-for-python/
    startLine: 15
  summary: "The diagnostic settings for service.\n\n:param storage_account_id: The\
    \ resource ID of the storage account to which\n you would like to send Diagnostic\
    \ Logs.\n:type storage_account_id: str\n:param service_bus_rule_id: The service\
    \ bus rule ID of the service bus\n namespace in which you would like to have Event\
    \ Hubs created for streaming\n Diagnostic Logs. The rule ID is of the format:\
    \ '{service bus resource\n ID}/authorizationrules/{key name}'.\n:type service_bus_rule_id:\
    \ str\n:param metrics: the list of metric settings.\n:type metrics: list of :class:`MetricSettings\n\
    \ <azure.mgmt.monitor.models.MetricSettings>`\n:param logs: the list of logs settings.\n\
    :type logs: list of :class:`LogSettings\n <azure.mgmt.monitor.models.LogSettings>`\n\
    :param workspace_id: The workspace ID (resource ID of a Log Analytics\n workspace)\
    \ for a Log Analytics workspace to which you would like to send\n Diagnostic Logs.\
    \ Example:\n /subscriptions/4b9e8510-67ab-4e9a-95a9-e2f1e570ea9c/resourceGroups/insights-integration/providers/Microsoft.OperationalInsights/workspaces/viruela2\n\
    :type workspace_id: str"
  type: Class
  uid: azure.mgmt.monitor.models.ServiceDiagnosticSettings
