api_name: []
items:
- _type: class
  children: []
  class: azure.mgmt.web.models.CorsSettings
  fullName: azure.mgmt.web.models.CorsSettings
  inheritance:
  - msrest.serialization.Model
  - builtins.object
  module: azure.mgmt.web.models
  name: CorsSettings
  source:
    id: CorsSettings
    path: azure-mgmt-web/azure/mgmt/web/models/cors_settings.py
    remote:
      branch: master
      path: azure-mgmt-web/azure/mgmt/web/models/cors_settings.py
      repo: git@github.com:ericholscher/azure-sdk-for-python.git
    startLine: 15
  summary: "Cross-Origin Resource Sharing (CORS) settings for the app.\n\n:param allowed_origins:\
    \ Gets or sets the list of origins that should be\n allowed to make cross-origin\n\
    \ calls (for example: http://example.com:12345). Use \"*\" to allow all.\n:type\
    \ allowed_origins: list of str"
  type: Class
  uid: azure.mgmt.web.models.CorsSettings
