api_name: []
items:
- _type: class
  children:
  - azure.mgmt.web.operations.ManagedHostingEnvironmentsOperations.create_or_update_managed_hosting_environment
  - azure.mgmt.web.operations.ManagedHostingEnvironmentsOperations.delete_managed_hosting_environment
  - azure.mgmt.web.operations.ManagedHostingEnvironmentsOperations.get_managed_hosting_environment
  - azure.mgmt.web.operations.ManagedHostingEnvironmentsOperations.get_managed_hosting_environment_operation
  - azure.mgmt.web.operations.ManagedHostingEnvironmentsOperations.get_managed_hosting_environment_server_farms
  - azure.mgmt.web.operations.ManagedHostingEnvironmentsOperations.get_managed_hosting_environment_sites
  - azure.mgmt.web.operations.ManagedHostingEnvironmentsOperations.get_managed_hosting_environment_vips
  - azure.mgmt.web.operations.ManagedHostingEnvironmentsOperations.get_managed_hosting_environment_web_hosting_plans
  - azure.mgmt.web.operations.ManagedHostingEnvironmentsOperations.get_managed_hosting_environments
  class: azure.mgmt.web.operations.ManagedHostingEnvironmentsOperations
  fullName: azure.mgmt.web.operations.ManagedHostingEnvironmentsOperations
  inheritance:
  - builtins.object
  module: azure.mgmt.web.operations
  name: ManagedHostingEnvironmentsOperations
  source:
    id: ManagedHostingEnvironmentsOperations
    path: azure-mgmt-web/azure/mgmt/web/operations/managed_hosting_environments_operations.py
    remote:
      branch: master
      path: azure-mgmt-web/azure/mgmt/web/operations/managed_hosting_environments_operations.py
      repo: https://github.com/Azure/azure-sdk-for-python/
    startLine: 20
  summary: 'ManagedHostingEnvironmentsOperations operations.


    :param client: Client for service requests.

    :param config: Configuration of service client.

    :param serializer: An object model serializer.

    :param deserializer: An objec model deserializer.'
  type: Class
  uid: azure.mgmt.web.operations.ManagedHostingEnvironmentsOperations
- _type: method
  class: azure.mgmt.web.operations.ManagedHostingEnvironmentsOperations
  fullName: azure.mgmt.web.operations.ManagedHostingEnvironmentsOperations.create_or_update_managed_hosting_environment
  module: azure.mgmt.web.operations
  name: create_or_update_managed_hosting_environment
  source:
    id: create_or_update_managed_hosting_environment
    path: azure-mgmt-web/azure/mgmt/web/operations/managed_hosting_environments_operations.py
    remote:
      branch: master
      path: azure-mgmt-web/azure/mgmt/web/operations/managed_hosting_environments_operations.py
      repo: https://github.com/Azure/azure-sdk-for-python/
    startLine: 99
  summary: "Create or update a managed hosting environment.\n\n:param resource_group_name:\
    \ Name of resource group\n:type resource_group_name: str\n:param name: Name of\
    \ managed hosting environment\n:type name: str\n:param managed_hosting_environment_envelope:\
    \ Properties of managed\n hosting environment\n:type managed_hosting_environment_envelope:\n\
    \ :class:`HostingEnvironment <azure.mgmt.web.models.HostingEnvironment>`\n:param\
    \ dict custom_headers: headers that will be added to the request\n:param bool\
    \ raw: returns the direct response alongside the\n deserialized response\n:rtype:\n\
    \ :class:`AzureOperationPoller<msrestazure.azure_operation.AzureOperationPoller>`\n\
    \ instance that returns :class:`HostingEnvironment\n <azure.mgmt.web.models.HostingEnvironment>`\n\
    :rtype: :class:`ClientRawResponse<msrest.pipeline.ClientRawResponse>`\n if raw=true\n\
    :raises: :class:`CloudError<msrestazure.azure_exceptions.CloudError>`"
  type: Method
  uid: azure.mgmt.web.operations.ManagedHostingEnvironmentsOperations.create_or_update_managed_hosting_environment
- _type: method
  class: azure.mgmt.web.operations.ManagedHostingEnvironmentsOperations
  fullName: azure.mgmt.web.operations.ManagedHostingEnvironmentsOperations.delete_managed_hosting_environment
  module: azure.mgmt.web.operations
  name: delete_managed_hosting_environment
  source:
    id: delete_managed_hosting_environment
    path: azure-mgmt-web/azure/mgmt/web/operations/managed_hosting_environments_operations.py
    remote:
      branch: master
      path: azure-mgmt-web/azure/mgmt/web/operations/managed_hosting_environments_operations.py
      repo: https://github.com/Azure/azure-sdk-for-python/
    startLine: 192
  summary: "Delete a managed hosting environment.\n\n:param resource_group_name: Name\
    \ of resource group\n:type resource_group_name: str\n:param name: Name of managed\
    \ hosting environment\n:type name: str\n:param force_delete: Delete even if the\
    \ managed hosting environment\n contains resources\n:type force_delete: bool\n\
    :param dict custom_headers: headers that will be added to the request\n:param\
    \ bool raw: returns the direct response alongside the\n deserialized response\n\
    :rtype:\n :class:`AzureOperationPoller<msrestazure.azure_operation.AzureOperationPoller>`\n\
    \ instance that returns object\n:rtype: :class:`ClientRawResponse<msrest.pipeline.ClientRawResponse>`\n\
    \ if raw=true\n:raises: :class:`CloudError<msrestazure.azure_exceptions.CloudError>`"
  type: Method
  uid: azure.mgmt.web.operations.ManagedHostingEnvironmentsOperations.delete_managed_hosting_environment
- _type: method
  class: azure.mgmt.web.operations.ManagedHostingEnvironmentsOperations
  fullName: azure.mgmt.web.operations.ManagedHostingEnvironmentsOperations.get_managed_hosting_environment
  module: azure.mgmt.web.operations
  name: get_managed_hosting_environment
  source:
    id: get_managed_hosting_environment
    path: azure-mgmt-web/azure/mgmt/web/operations/managed_hosting_environments_operations.py
    remote:
      branch: master
      path: azure-mgmt-web/azure/mgmt/web/operations/managed_hosting_environments_operations.py
      repo: https://github.com/Azure/azure-sdk-for-python/
    startLine: 37
  summary: "Get properties of a managed hosting environment.\n\n:param resource_group_name:\
    \ Name of resource group\n:type resource_group_name: str\n:param name: Name of\
    \ managed hosting environment\n:type name: str\n:param dict custom_headers: headers\
    \ that will be added to the request\n:param bool raw: returns the direct response\
    \ alongside the\n deserialized response\n:param operation_config: :ref:`Operation\
    \ configuration\n overrides<msrest:optionsforoperations>`.\n:rtype: :class:`ManagedHostingEnvironment\n\
    \ <azure.mgmt.web.models.ManagedHostingEnvironment>`\n:rtype: :class:`ClientRawResponse<msrest.pipeline.ClientRawResponse>`\n\
    \ if raw=true\n:raises: :class:`CloudError<msrestazure.azure_exceptions.CloudError>`"
  type: Method
  uid: azure.mgmt.web.operations.ManagedHostingEnvironmentsOperations.get_managed_hosting_environment
- _type: method
  class: azure.mgmt.web.operations.ManagedHostingEnvironmentsOperations
  fullName: azure.mgmt.web.operations.ManagedHostingEnvironmentsOperations.get_managed_hosting_environment_operation
  module: azure.mgmt.web.operations
  name: get_managed_hosting_environment_operation
  source:
    id: get_managed_hosting_environment_operation
    path: azure-mgmt-web/azure/mgmt/web/operations/managed_hosting_environments_operations.py
    remote:
      branch: master
      path: azure-mgmt-web/azure/mgmt/web/operations/managed_hosting_environments_operations.py
      repo: https://github.com/Azure/azure-sdk-for-python/
    startLine: 409
  summary: "Get status of an operation on a managed hosting environment.\n\n:param\
    \ resource_group_name: Name of resource group\n:type resource_group_name: str\n\
    :param name: Name of managed hosting environment\n:type name: str\n:param operation_id:\
    \ operation identifier GUID\n:type operation_id: str\n:param dict custom_headers:\
    \ headers that will be added to the request\n:param bool raw: returns the direct\
    \ response alongside the\n deserialized response\n:param operation_config: :ref:`Operation\
    \ configuration\n overrides<msrest:optionsforoperations>`.\n:rtype: object\n:rtype:\
    \ :class:`ClientRawResponse<msrest.pipeline.ClientRawResponse>`\n if raw=true\n\
    :raises: :class:`CloudError<msrestazure.azure_exceptions.CloudError>`"
  type: Method
  uid: azure.mgmt.web.operations.ManagedHostingEnvironmentsOperations.get_managed_hosting_environment_operation
- _type: method
  class: azure.mgmt.web.operations.ManagedHostingEnvironmentsOperations
  fullName: azure.mgmt.web.operations.ManagedHostingEnvironmentsOperations.get_managed_hosting_environment_server_farms
  module: azure.mgmt.web.operations
  name: get_managed_hosting_environment_server_farms
  source:
    id: get_managed_hosting_environment_server_farms
    path: azure-mgmt-web/azure/mgmt/web/operations/managed_hosting_environments_operations.py
    remote:
      branch: master
      path: azure-mgmt-web/azure/mgmt/web/operations/managed_hosting_environments_operations.py
      repo: https://github.com/Azure/azure-sdk-for-python/
    startLine: 618
  summary: "Get all serverfarms (App Service Plans) on the managed hosting\nenvironment.\n\
    \n:param resource_group_name: Name of resource group\n:type resource_group_name:\
    \ str\n:param name: Name of managed hosting environment\n:type name: str\n:param\
    \ dict custom_headers: headers that will be added to the request\n:param bool\
    \ raw: returns the direct response alongside the\n deserialized response\n:param\
    \ operation_config: :ref:`Operation configuration\n overrides<msrest:optionsforoperations>`.\n\
    :rtype: :class:`ServerFarmWithRichSkuPaged\n <azure.mgmt.web.models.ServerFarmWithRichSkuPaged>`\n\
    :raises: :class:`CloudError<msrestazure.azure_exceptions.CloudError>`"
  type: Method
  uid: azure.mgmt.web.operations.ManagedHostingEnvironmentsOperations.get_managed_hosting_environment_server_farms
- _type: method
  class: azure.mgmt.web.operations.ManagedHostingEnvironmentsOperations
  fullName: azure.mgmt.web.operations.ManagedHostingEnvironmentsOperations.get_managed_hosting_environment_sites
  module: azure.mgmt.web.operations
  name: get_managed_hosting_environment_sites
  source:
    id: get_managed_hosting_environment_sites
    path: azure-mgmt-web/azure/mgmt/web/operations/managed_hosting_environments_operations.py
    remote:
      branch: master
      path: azure-mgmt-web/azure/mgmt/web/operations/managed_hosting_environments_operations.py
      repo: https://github.com/Azure/azure-sdk-for-python/
    startLine: 475
  summary: "Get all sites on the managed hosting environment.\n\n:param resource_group_name:\
    \ Name of resource group\n:type resource_group_name: str\n:param name: Name of\
    \ managed hosting environment\n:type name: str\n:param properties_to_include:\
    \ Comma separated list of site properties\n to include\n:type properties_to_include:\
    \ str\n:param dict custom_headers: headers that will be added to the request\n\
    :param bool raw: returns the direct response alongside the\n deserialized response\n\
    :param operation_config: :ref:`Operation configuration\n overrides<msrest:optionsforoperations>`.\n\
    :rtype: :class:`SitePaged <azure.mgmt.web.models.SitePaged>`\n:raises: :class:`CloudError<msrestazure.azure_exceptions.CloudError>`"
  type: Method
  uid: azure.mgmt.web.operations.ManagedHostingEnvironmentsOperations.get_managed_hosting_environment_sites
- _type: method
  class: azure.mgmt.web.operations.ManagedHostingEnvironmentsOperations
  fullName: azure.mgmt.web.operations.ManagedHostingEnvironmentsOperations.get_managed_hosting_environment_vips
  module: azure.mgmt.web.operations
  name: get_managed_hosting_environment_vips
  source:
    id: get_managed_hosting_environment_vips
    path: azure-mgmt-web/azure/mgmt/web/operations/managed_hosting_environments_operations.py
    remote:
      branch: master
      path: azure-mgmt-web/azure/mgmt/web/operations/managed_hosting_environments_operations.py
      repo: https://github.com/Azure/azure-sdk-for-python/
    startLine: 347
  summary: "Get list of ip addresses assigned to a managed hosting environment.\n\n\
    :param resource_group_name: Name of resource group\n:type resource_group_name:\
    \ str\n:param name: Name of managed hosting environment\n:type name: str\n:param\
    \ dict custom_headers: headers that will be added to the request\n:param bool\
    \ raw: returns the direct response alongside the\n deserialized response\n:param\
    \ operation_config: :ref:`Operation configuration\n overrides<msrest:optionsforoperations>`.\n\
    :rtype: :class:`AddressResponse\n <azure.mgmt.web.models.AddressResponse>`\n:rtype:\
    \ :class:`ClientRawResponse<msrest.pipeline.ClientRawResponse>`\n if raw=true\n\
    :raises: :class:`CloudError<msrestazure.azure_exceptions.CloudError>`"
  type: Method
  uid: azure.mgmt.web.operations.ManagedHostingEnvironmentsOperations.get_managed_hosting_environment_vips
- _type: method
  class: azure.mgmt.web.operations.ManagedHostingEnvironmentsOperations
  fullName: azure.mgmt.web.operations.ManagedHostingEnvironmentsOperations.get_managed_hosting_environment_web_hosting_plans
  module: azure.mgmt.web.operations
  name: get_managed_hosting_environment_web_hosting_plans
  source:
    id: get_managed_hosting_environment_web_hosting_plans
    path: azure-mgmt-web/azure/mgmt/web/operations/managed_hosting_environments_operations.py
    remote:
      branch: master
      path: azure-mgmt-web/azure/mgmt/web/operations/managed_hosting_environments_operations.py
      repo: https://github.com/Azure/azure-sdk-for-python/
    startLine: 548
  summary: "Get all serverfarms (App Service Plans) on the managed hosting\nenvironment.\n\
    \n:param resource_group_name: Name of resource group\n:type resource_group_name:\
    \ str\n:param name: Name of managed hosting environment\n:type name: str\n:param\
    \ dict custom_headers: headers that will be added to the request\n:param bool\
    \ raw: returns the direct response alongside the\n deserialized response\n:param\
    \ operation_config: :ref:`Operation configuration\n overrides<msrest:optionsforoperations>`.\n\
    :rtype: :class:`ServerFarmWithRichSkuPaged\n <azure.mgmt.web.models.ServerFarmWithRichSkuPaged>`\n\
    :raises: :class:`CloudError<msrestazure.azure_exceptions.CloudError>`"
  type: Method
  uid: azure.mgmt.web.operations.ManagedHostingEnvironmentsOperations.get_managed_hosting_environment_web_hosting_plans
- _type: method
  class: azure.mgmt.web.operations.ManagedHostingEnvironmentsOperations
  fullName: azure.mgmt.web.operations.ManagedHostingEnvironmentsOperations.get_managed_hosting_environments
  module: azure.mgmt.web.operations
  name: get_managed_hosting_environments
  source:
    id: get_managed_hosting_environments
    path: azure-mgmt-web/azure/mgmt/web/operations/managed_hosting_environments_operations.py
    remote:
      branch: master
      path: azure-mgmt-web/azure/mgmt/web/operations/managed_hosting_environments_operations.py
      repo: https://github.com/Azure/azure-sdk-for-python/
    startLine: 281
  summary: "Get all managed hosting environments in a resource group.\n\n:param resource_group_name:\
    \ Name of resource group\n:type resource_group_name: str\n:param dict custom_headers:\
    \ headers that will be added to the request\n:param bool raw: returns the direct\
    \ response alongside the\n deserialized response\n:param operation_config: :ref:`Operation\
    \ configuration\n overrides<msrest:optionsforoperations>`.\n:rtype: :class:`HostingEnvironmentPaged\n\
    \ <azure.mgmt.web.models.HostingEnvironmentPaged>`\n:raises: :class:`CloudError<msrestazure.azure_exceptions.CloudError>`"
  type: Method
  uid: azure.mgmt.web.operations.ManagedHostingEnvironmentsOperations.get_managed_hosting_environments
