api_name: []
items:
- _type: class
  children: []
  class: azure.mgmt.web.models.FileSystemHttpLogsConfig
  fullName: azure.mgmt.web.models.FileSystemHttpLogsConfig
  inheritance:
  - msrest.serialization.Model
  - builtins.object
  module: azure.mgmt.web.models
  name: FileSystemHttpLogsConfig
  source:
    id: FileSystemHttpLogsConfig
    path: azure-mgmt-web/azure/mgmt/web/models/file_system_http_logs_config.py
    remote:
      branch: master
      path: azure-mgmt-web/azure/mgmt/web/models/file_system_http_logs_config.py
      repo: git@github.com:ericholscher/azure-sdk-for-python.git
    startLine: 15
  summary: "Http logs to file system configuration.\n\n:param retention_in_mb: Maximum\
    \ size in megabytes that http log files can\n use.\n When reached old log files\
    \ will be removed to make space for new ones.\n Value can range between 25 and\
    \ 100.\n:type retention_in_mb: int\n:param retention_in_days: Retention in days.\n\
    \ Remove files older than X days.\n 0 or lower means no retention.\n:type retention_in_days:\
    \ int\n:param enabled: Enabled.\n:type enabled: bool"
  type: Class
  uid: azure.mgmt.web.models.FileSystemHttpLogsConfig
