api_name: []
items:
- _type: class
  children: []
  class: azure.mgmt.logic.models.AS2EnvelopeSettings
  fullName: azure.mgmt.logic.models.AS2EnvelopeSettings
  inheritance:
  - msrest.serialization.Model
  - builtins.object
  module: azure.mgmt.logic.models
  name: AS2EnvelopeSettings
  source:
    id: AS2EnvelopeSettings
    path: Users/eric/.virtualenvs/sphinx-docfx-yaml/lib/python3.5/site-packages/azure/mgmt/logic/models/as2_envelope_settings.py
    remote:
      branch: master
      path: Users/eric/.virtualenvs/sphinx-docfx-yaml/lib/python3.5/site-packages/azure/mgmt/logic/models/as2_envelope_settings.py
      repo: git@github.com:ericholscher/azure-sdk-for-python.git
    startLine: 15
  summary: "AS2EnvelopeSettings.\n\n:param message_content_type: The message content\
    \ type.\n:type message_content_type: str\n:param transmit_file_name_in_mime_header:\
    \ The value indicating whether to\n transmit file name in mime header.\n:type\
    \ transmit_file_name_in_mime_header: bool\n:param file_name_template: The template\
    \ for file name.\n:type file_name_template: str\n:param suspend_message_on_file_name_generation_error:\
    \ The value\n indicating whether to suspend message on file name generation error.\n\
    :type suspend_message_on_file_name_generation_error: bool\n:param autogenerate_file_name:\
    \ The value indicating whether to auto\n generate file name.\n:type autogenerate_file_name:\
    \ bool"
  type: Class
  uid: azure.mgmt.logic.models.AS2EnvelopeSettings
