api_name: []
items:
- _type: class
  children: []
  class: azure.batch.models.ApplicationSummary
  fullName: azure.batch.models.ApplicationSummary
  inheritance:
  - msrest.serialization.Model
  - builtins.object
  module: azure.batch.models
  name: ApplicationSummary
  source:
    id: ApplicationSummary
    path: Users/eric/.virtualenvs/sphinx-docfx-yaml/lib/python3.5/site-packages/azure/batch/models/application_summary.py
    remote:
      branch: master
      path: Users/eric/.virtualenvs/sphinx-docfx-yaml/lib/python3.5/site-packages/azure/batch/models/application_summary.py
      repo: https://github.com/Azure/azure-sdk-for-python/
    startLine: 15
  summary: "Contains information about an application in an Azure Batch account.\n\
    \n:param id: A string that uniquely identifies the application within the\n account.\n\
    :type id: str\n:param display_name: The display name for the application.\n:type\
    \ display_name: str\n:param versions: The versions of the application which are\
    \ available.\n:type versions: list of str"
  type: Class
  uid: azure.batch.models.ApplicationSummary
