api_name: []
items:
- _type: class
  children: []
  class: azure.mgmt.batch.models.AddApplicationPackageResult
  fullName: azure.mgmt.batch.models.AddApplicationPackageResult
  inheritance:
  - msrest.serialization.Model
  - builtins.object
  module: azure.mgmt.batch.models
  name: AddApplicationPackageResult
  source:
    id: AddApplicationPackageResult
    path: Users/eric/.virtualenvs/sphinx-docfx-yaml/lib/python3.5/site-packages/azure/mgmt/batch/models/add_application_package_result.py
    remote:
      branch: master
      path: Users/eric/.virtualenvs/sphinx-docfx-yaml/lib/python3.5/site-packages/azure/mgmt/batch/models/add_application_package_result.py
      repo: https://github.com/Azure/azure-sdk-for-python/
    startLine: 15
  summary: "Response to an ApplicationOperations.AddApplicationPackage request.\n\n\
    :param id: The id of the application.\n:type id: str\n:param version: The version\
    \ of the application.\n:type version: str\n:param storage_url: The URL to which\
    \ the application package binary file\n should be uploaded.\n:type storage_url:\
    \ str\n:param storage_url_expiry: The UTC time at which the storage URL will\n\
    \ expire.\n:type storage_url_expiry: datetime"
  type: Class
  uid: azure.mgmt.batch.models.AddApplicationPackageResult
