api_name: []
items:
- _type: class
  children:
  - azure.mgmt.network.operations.ApplicationGatewaysOperations.create_or_update
  - azure.mgmt.network.operations.ApplicationGatewaysOperations.delete
  - azure.mgmt.network.operations.ApplicationGatewaysOperations.get
  - azure.mgmt.network.operations.ApplicationGatewaysOperations.list
  - azure.mgmt.network.operations.ApplicationGatewaysOperations.list_all
  - azure.mgmt.network.operations.ApplicationGatewaysOperations.start
  - azure.mgmt.network.operations.ApplicationGatewaysOperations.stop
  class: azure.mgmt.network.operations.ApplicationGatewaysOperations
  fullName: azure.mgmt.network.operations.ApplicationGatewaysOperations
  inheritance:
  - builtins.object
  module: azure.mgmt.network.operations
  name: ApplicationGatewaysOperations
  source:
    id: ApplicationGatewaysOperations
    path: Users/eric/.virtualenvs/sphinx-docfx-yaml/lib/python3.5/site-packages/azure/mgmt/network/operations/application_gateways_operations.py
    remote:
      branch: master
      path: Users/eric/.virtualenvs/sphinx-docfx-yaml/lib/python3.5/site-packages/azure/mgmt/network/operations/application_gateways_operations.py
      repo: https://github.com/Azure/azure-sdk-for-python/
    startLine: 20
  summary: 'ApplicationGatewaysOperations operations.


    :param client: Client for service requests.

    :param config: Configuration of service client.

    :param serializer: An object model serializer.

    :param deserializer: An objec model deserializer.'
  type: Class
  uid: azure.mgmt.network.operations.ApplicationGatewaysOperations
- _type: method
  class: azure.mgmt.network.operations.ApplicationGatewaysOperations
  fullName: azure.mgmt.network.operations.ApplicationGatewaysOperations.create_or_update
  module: azure.mgmt.network.operations
  name: create_or_update
  source:
    id: create_or_update
    path: Users/eric/.virtualenvs/sphinx-docfx-yaml/lib/python3.5/site-packages/azure/mgmt/network/operations/application_gateways_operations.py
    remote:
      branch: master
      path: Users/eric/.virtualenvs/sphinx-docfx-yaml/lib/python3.5/site-packages/azure/mgmt/network/operations/application_gateways_operations.py
      repo: https://github.com/Azure/azure-sdk-for-python/
    startLine: 176
  summary: "The Put ApplicationGateway operation creates/updates a\nApplicationGateway.\n\
    \n:param resource_group_name: The name of the resource group.\n:type resource_group_name:\
    \ str\n:param application_gateway_name: The name of the ApplicationGateway.\n\
    :type application_gateway_name: str\n:param parameters: Parameters supplied to\
    \ the create/delete\n ApplicationGateway operation\n:type parameters: :class:`ApplicationGateway\n\
    \ <azure.mgmt.network.models.ApplicationGateway>`\n:param dict custom_headers:\
    \ headers that will be added to the request\n:param bool raw: returns the direct\
    \ response alongside the\n deserialized response\n:rtype:\n :class:`AzureOperationPoller<msrestazure.azure_operation.AzureOperationPoller>`\n\
    \ instance that returns :class:`ApplicationGateway\n <azure.mgmt.network.models.ApplicationGateway>`\n\
    :rtype: :class:`ClientRawResponse<msrest.pipeline.ClientRawResponse>`\n if raw=true"
  type: Method
  uid: azure.mgmt.network.operations.ApplicationGatewaysOperations.create_or_update
- _type: method
  class: azure.mgmt.network.operations.ApplicationGatewaysOperations
  fullName: azure.mgmt.network.operations.ApplicationGatewaysOperations.delete
  module: azure.mgmt.network.operations
  name: delete
  source:
    id: delete
    path: Users/eric/.virtualenvs/sphinx-docfx-yaml/lib/python3.5/site-packages/azure/mgmt/network/operations/application_gateways_operations.py
    remote:
      branch: master
      path: Users/eric/.virtualenvs/sphinx-docfx-yaml/lib/python3.5/site-packages/azure/mgmt/network/operations/application_gateways_operations.py
      repo: https://github.com/Azure/azure-sdk-for-python/
    startLine: 37
  summary: "The delete ApplicationGateway operation deletes the specified\napplication\
    \ gateway.\n\n:param resource_group_name: The name of the resource group.\n:type\
    \ resource_group_name: str\n:param application_gateway_name: The name of the application\
    \ gateway.\n:type application_gateway_name: str\n:param dict custom_headers: headers\
    \ that will be added to the request\n:param bool raw: returns the direct response\
    \ alongside the\n deserialized response\n:rtype:\n :class:`AzureOperationPoller<msrestazure.azure_operation.AzureOperationPoller>`\n\
    \ instance that returns None\n:rtype: :class:`ClientRawResponse<msrest.pipeline.ClientRawResponse>`\n\
    \ if raw=true"
  type: Method
  uid: azure.mgmt.network.operations.ApplicationGatewaysOperations.delete
- _type: method
  class: azure.mgmt.network.operations.ApplicationGatewaysOperations
  fullName: azure.mgmt.network.operations.ApplicationGatewaysOperations.get
  module: azure.mgmt.network.operations
  name: get
  source:
    id: get
    path: Users/eric/.virtualenvs/sphinx-docfx-yaml/lib/python3.5/site-packages/azure/mgmt/network/operations/application_gateways_operations.py
    remote:
      branch: master
      path: Users/eric/.virtualenvs/sphinx-docfx-yaml/lib/python3.5/site-packages/azure/mgmt/network/operations/application_gateways_operations.py
      repo: https://github.com/Azure/azure-sdk-for-python/
    startLine: 114
  summary: "The Get ApplicationGateway operation retrieves information about the\n\
    specified application gateway.\n\n:param resource_group_name: The name of the\
    \ resource group.\n:type resource_group_name: str\n:param application_gateway_name:\
    \ The name of the application gateway.\n:type application_gateway_name: str\n\
    :param dict custom_headers: headers that will be added to the request\n:param\
    \ bool raw: returns the direct response alongside the\n deserialized response\n\
    :param operation_config: :ref:`Operation configuration\n overrides<msrest:optionsforoperations>`.\n\
    :rtype: :class:`ApplicationGateway\n <azure.mgmt.network.models.ApplicationGateway>`\n\
    :rtype: :class:`ClientRawResponse<msrest.pipeline.ClientRawResponse>`\n if raw=true"
  type: Method
  uid: azure.mgmt.network.operations.ApplicationGatewaysOperations.get
- _type: method
  class: azure.mgmt.network.operations.ApplicationGatewaysOperations
  fullName: azure.mgmt.network.operations.ApplicationGatewaysOperations.list
  module: azure.mgmt.network.operations
  name: list
  source:
    id: list
    path: Users/eric/.virtualenvs/sphinx-docfx-yaml/lib/python3.5/site-packages/azure/mgmt/network/operations/application_gateways_operations.py
    remote:
      branch: master
      path: Users/eric/.virtualenvs/sphinx-docfx-yaml/lib/python3.5/site-packages/azure/mgmt/network/operations/application_gateways_operations.py
      repo: https://github.com/Azure/azure-sdk-for-python/
    startLine: 271
  summary: "The List ApplicationGateway operation retrieves all the application\n\
    gateways in a resource group.\n\n:param resource_group_name: The name of the resource\
    \ group.\n:type resource_group_name: str\n:param dict custom_headers: headers\
    \ that will be added to the request\n:param bool raw: returns the direct response\
    \ alongside the\n deserialized response\n:param operation_config: :ref:`Operation\
    \ configuration\n overrides<msrest:optionsforoperations>`.\n:rtype: :class:`ApplicationGatewayPaged\n\
    \ <azure.mgmt.network.models.ApplicationGatewayPaged>`"
  type: Method
  uid: azure.mgmt.network.operations.ApplicationGatewaysOperations.list
- _type: method
  class: azure.mgmt.network.operations.ApplicationGatewaysOperations
  fullName: azure.mgmt.network.operations.ApplicationGatewaysOperations.list_all
  module: azure.mgmt.network.operations
  name: list_all
  source:
    id: list_all
    path: Users/eric/.virtualenvs/sphinx-docfx-yaml/lib/python3.5/site-packages/azure/mgmt/network/operations/application_gateways_operations.py
    remote:
      branch: master
      path: Users/eric/.virtualenvs/sphinx-docfx-yaml/lib/python3.5/site-packages/azure/mgmt/network/operations/application_gateways_operations.py
      repo: https://github.com/Azure/azure-sdk-for-python/
    startLine: 337
  summary: "The List ApplicationGateway operation retrieves all the application\n\
    gateways in a subscription.\n\n:param dict custom_headers: headers that will be\
    \ added to the request\n:param bool raw: returns the direct response alongside\
    \ the\n deserialized response\n:param operation_config: :ref:`Operation configuration\n\
    \ overrides<msrest:optionsforoperations>`.\n:rtype: :class:`ApplicationGatewayPaged\n\
    \ <azure.mgmt.network.models.ApplicationGatewayPaged>`"
  type: Method
  uid: azure.mgmt.network.operations.ApplicationGatewaysOperations.list_all
- _type: method
  class: azure.mgmt.network.operations.ApplicationGatewaysOperations
  fullName: azure.mgmt.network.operations.ApplicationGatewaysOperations.start
  module: azure.mgmt.network.operations
  name: start
  source:
    id: start
    path: Users/eric/.virtualenvs/sphinx-docfx-yaml/lib/python3.5/site-packages/azure/mgmt/network/operations/application_gateways_operations.py
    remote:
      branch: master
      path: Users/eric/.virtualenvs/sphinx-docfx-yaml/lib/python3.5/site-packages/azure/mgmt/network/operations/application_gateways_operations.py
      repo: https://github.com/Azure/azure-sdk-for-python/
    startLine: 400
  summary: "The Start ApplicationGateway operation starts application gateway in\n\
    the specified resource group through Network resource provider.\n\n:param resource_group_name:\
    \ The name of the resource group.\n:type resource_group_name: str\n:param application_gateway_name:\
    \ The name of the application gateway.\n:type application_gateway_name: str\n\
    :param dict custom_headers: headers that will be added to the request\n:param\
    \ bool raw: returns the direct response alongside the\n deserialized response\n\
    :rtype:\n :class:`AzureOperationPoller<msrestazure.azure_operation.AzureOperationPoller>`\n\
    \ instance that returns None\n:rtype: :class:`ClientRawResponse<msrest.pipeline.ClientRawResponse>`\n\
    \ if raw=true"
  type: Method
  uid: azure.mgmt.network.operations.ApplicationGatewaysOperations.start
- _type: method
  class: azure.mgmt.network.operations.ApplicationGatewaysOperations
  fullName: azure.mgmt.network.operations.ApplicationGatewaysOperations.stop
  module: azure.mgmt.network.operations
  name: stop
  source:
    id: stop
    path: Users/eric/.virtualenvs/sphinx-docfx-yaml/lib/python3.5/site-packages/azure/mgmt/network/operations/application_gateways_operations.py
    remote:
      branch: master
      path: Users/eric/.virtualenvs/sphinx-docfx-yaml/lib/python3.5/site-packages/azure/mgmt/network/operations/application_gateways_operations.py
      repo: https://github.com/Azure/azure-sdk-for-python/
    startLine: 477
  summary: "The STOP ApplicationGateway operation stops application gateway in the\n\
    specified resource group through Network resource provider.\n\n:param resource_group_name:\
    \ The name of the resource group.\n:type resource_group_name: str\n:param application_gateway_name:\
    \ The name of the application gateway.\n:type application_gateway_name: str\n\
    :param dict custom_headers: headers that will be added to the request\n:param\
    \ bool raw: returns the direct response alongside the\n deserialized response\n\
    :rtype:\n :class:`AzureOperationPoller<msrestazure.azure_operation.AzureOperationPoller>`\n\
    \ instance that returns None\n:rtype: :class:`ClientRawResponse<msrest.pipeline.ClientRawResponse>`\n\
    \ if raw=true"
  type: Method
  uid: azure.mgmt.network.operations.ApplicationGatewaysOperations.stop
