api_name: []
items:
- _type: class
  children: []
  class: azure.graphrbac.models.ApplicationPaged
  fullName: azure.graphrbac.models.ApplicationPaged
  inheritance:
  - msrest.paging.Paged
  - collections.abc.Iterator
  - collections.abc.Iterable
  - builtins.object
  module: azure.graphrbac.models
  name: ApplicationPaged
  source:
    id: ApplicationPaged
    path: azure-graphrbac/azure/graphrbac/models/application_paged.py
    remote:
      branch: master
      path: azure-graphrbac/azure/graphrbac/models/application_paged.py
      repo: git@github.com:ericholscher/azure-sdk-for-python.git
    startLine: 15
  summary: A paging container for iterating over a list of Application object
  type: Class
  uid: azure.graphrbac.models.ApplicationPaged
