api_name: []
items:
- _type: class
  children: []
  class: azure.mgmt.web.models.VirtualApplication
  fullName: azure.mgmt.web.models.VirtualApplication
  inheritance:
  - msrest.serialization.Model
  - builtins.object
  module: azure.mgmt.web.models
  name: VirtualApplication
  source:
    id: VirtualApplication
    path: azure-mgmt-web/azure/mgmt/web/models/virtual_application.py
    remote:
      branch: master
      path: azure-mgmt-web/azure/mgmt/web/models/virtual_application.py
      repo: https://github.com/Azure/azure-sdk-for-python/
    startLine: 15
  summary: "VirtualApplication.\n\n:param virtual_path:\n:type virtual_path: str\n\
    :param physical_path:\n:type physical_path: str\n:param preload_enabled:\n:type\
    \ preload_enabled: bool\n:param virtual_directories:\n:type virtual_directories:\
    \ list of :class:`VirtualDirectory\n <azure.mgmt.web.models.VirtualDirectory>`"
  type: Class
  uid: azure.mgmt.web.models.VirtualApplication
