api_name: []
items:
- _type: class
  children: []
  class: azure.batch.models.EnvironmentSetting
  fullName: azure.batch.models.EnvironmentSetting
  inheritance:
  - msrest.serialization.Model
  - builtins.object
  module: azure.batch.models
  name: EnvironmentSetting
  source:
    id: EnvironmentSetting
    path: Users/eric/.virtualenvs/sphinx-docfx-yaml/lib/python3.5/site-packages/azure/batch/models/environment_setting.py
    remote:
      branch: master
      path: Users/eric/.virtualenvs/sphinx-docfx-yaml/lib/python3.5/site-packages/azure/batch/models/environment_setting.py
      repo: https://github.com/Azure/azure-sdk-for-python/
    startLine: 15
  summary: 'An environment variable to be set on a task process.


    :param name: The name of the environment variable.

    :type name: str

    :param value: The value of the environment variable.

    :type value: str'
  type: Class
  uid: azure.batch.models.EnvironmentSetting
