api_name: []
items:
- _type: class
  children: []
  class: azure.servicemanagement.models.ComponentSettings
  fullName: azure.servicemanagement.models.ComponentSettings
  inheritance:
  - azure.servicemanagement._common_models.WindowsAzureData
  - builtins.object
  module: azure.servicemanagement.models
  name: ComponentSettings
  source:
    id: ComponentSettings
    path: Users/eric/.virtualenvs/sphinx-docfx-yaml/lib/python3.5/site-packages/azure/servicemanagement/models.py
    remote:
      branch: master
      path: Users/eric/.virtualenvs/sphinx-docfx-yaml/lib/python3.5/site-packages/azure/servicemanagement/models.py
      repo: git@github.com:ericholscher/azure-sdk-for-python.git
    startLine: 628
  summary: ''
  type: Class
  uid: azure.servicemanagement.models.ComponentSettings
