api_name: []
items:
- _type: class
  children: []
  class: azure.mgmt.web.models.HttpLogsConfig
  fullName: azure.mgmt.web.models.HttpLogsConfig
  inheritance:
  - msrest.serialization.Model
  - builtins.object
  module: azure.mgmt.web.models
  name: HttpLogsConfig
  source:
    id: HttpLogsConfig
    path: azure-mgmt-web/azure/mgmt/web/models/http_logs_config.py
    remote:
      branch: master
      path: azure-mgmt-web/azure/mgmt/web/models/http_logs_config.py
      repo: git@github.com:ericholscher/azure-sdk-for-python.git
    startLine: 15
  summary: "Http logs configuration.\n\n:param file_system: Http logs to file system\
    \ configuration.\n:type file_system: :class:`FileSystemHttpLogsConfig\n <azure.mgmt.web.models.FileSystemHttpLogsConfig>`\n\
    :param azure_blob_storage: Http logs to azure blob storage configuration.\n:type\
    \ azure_blob_storage: :class:`AzureBlobStorageHttpLogsConfig\n <azure.mgmt.web.models.AzureBlobStorageHttpLogsConfig>`"
  type: Class
  uid: azure.mgmt.web.models.HttpLogsConfig
