api_name: []
items:
- _type: class
  children: []
  class: azure.mgmt.logic.models.X12ProcessingSettings
  fullName: azure.mgmt.logic.models.X12ProcessingSettings
  inheritance:
  - msrest.serialization.Model
  - builtins.object
  module: azure.mgmt.logic.models
  name: X12ProcessingSettings
  source:
    id: X12ProcessingSettings
    path: Users/eric/.virtualenvs/sphinx-docfx-yaml/lib/python3.5/site-packages/azure/mgmt/logic/models/x12_processing_settings.py
    remote:
      branch: master
      path: Users/eric/.virtualenvs/sphinx-docfx-yaml/lib/python3.5/site-packages/azure/mgmt/logic/models/x12_processing_settings.py
      repo: git@github.com:ericholscher/azure-sdk-for-python.git
    startLine: 15
  summary: "X12ProcessingSettings.\n\n:param mask_security_info: The value indicating\
    \ whether to mask security\n information.\n:type mask_security_info: bool\n:param\
    \ convert_implied_decimal: The value indicating whether to convert\n numerical\
    \ type to implied decimal.\n:type convert_implied_decimal: bool\n:param preserve_interchange:\
    \ The value indicating whether to preserve\n interchange.\n:type preserve_interchange:\
    \ bool\n:param suspend_interchange_on_error: The value indicating whether to\n\
    \ suspend interchange on error.\n:type suspend_interchange_on_error: bool\n:param\
    \ create_empty_xml_tags_for_trailing_separators: The value\n indicating whether\
    \ to create empty xml tags for trailing separators.\n:type create_empty_xml_tags_for_trailing_separators:\
    \ bool\n:param use_dot_as_decimal_separator: The value indicating whether to use\n\
    \ dot as decimal separator.\n:type use_dot_as_decimal_separator: bool"
  type: Class
  uid: azure.mgmt.logic.models.X12ProcessingSettings
