api_name: []
items:
- _type: class
  children: []
  class: azure.mgmt.web.models.EnabledConfig
  fullName: azure.mgmt.web.models.EnabledConfig
  inheritance:
  - msrest.serialization.Model
  - builtins.object
  module: azure.mgmt.web.models
  name: EnabledConfig
  source:
    id: EnabledConfig
    path: azure-mgmt-web/azure/mgmt/web/models/enabled_config.py
    remote:
      branch: master
      path: azure-mgmt-web/azure/mgmt/web/models/enabled_config.py
      repo: https://github.com/Azure/azure-sdk-for-python/
    startLine: 15
  summary: 'Enabled configuration.


    :param enabled: Enabled

    :type enabled: bool'
  type: Class
  uid: azure.mgmt.web.models.EnabledConfig
