api_name: []
items:
- _type: class
  children: []
  class: azure.mgmt.network.models.ApplicationGatewayOperationalState
  fullName: azure.mgmt.network.models.ApplicationGatewayOperationalState
  inheritance:
  - enum.Enum
  - builtins.object
  module: azure.mgmt.network.models
  name: ApplicationGatewayOperationalState
  source:
    id: ApplicationGatewayOperationalState
    path: Users/eric/.virtualenvs/sphinx-docfx-yaml/lib/python3.5/site-packages/azure/mgmt/network/models/network_management_client_enums.py
    remote:
      branch: master
      path: Users/eric/.virtualenvs/sphinx-docfx-yaml/lib/python3.5/site-packages/azure/mgmt/network/models/network_management_client_enums.py
      repo: https://github.com/Azure/azure-sdk-for-python/
    startLine: 98
  summary: An enumeration.
  type: Class
  uid: azure.mgmt.network.models.ApplicationGatewayOperationalState
