api_name: []
items:
- _type: class
  children: []
  class: azure.mgmt.batch.models.Application
  fullName: azure.mgmt.batch.models.Application
  inheritance:
  - msrest.serialization.Model
  - builtins.object
  module: azure.mgmt.batch.models
  name: Application
  source:
    id: Application
    path: Users/eric/.virtualenvs/sphinx-docfx-yaml/lib/python3.5/site-packages/azure/mgmt/batch/models/application.py
    remote:
      branch: master
      path: Users/eric/.virtualenvs/sphinx-docfx-yaml/lib/python3.5/site-packages/azure/mgmt/batch/models/application.py
      repo: https://github.com/Azure/azure-sdk-for-python/
    startLine: 15
  summary: "Contains information about an application in a Batch account.\n\n:param\
    \ id: A string that uniquely identifies the application within the\n account.\n\
    :type id: str\n:param display_name: The display name for the application.\n:type\
    \ display_name: str\n:param packages: The list of packages under this application.\n\
    :type packages: list of :class:`ApplicationPackage\n <azure.mgmt.batch.models.ApplicationPackage>`\n\
    :param allow_updates: A value indicating whether packages within the\n application\
    \ may be overwritten using the same version string.\n:type allow_updates: bool\n\
    :param default_version: The package to use if a client requests the\n application\
    \ but does not specify a version.\n:type default_version: str"
  type: Class
  uid: azure.mgmt.batch.models.Application
