api_name: []
items:
- _type: class
  children: []
  class: azure.mgmt.network.models.ApplicationGatewaySslCertificate
  fullName: azure.mgmt.network.models.ApplicationGatewaySslCertificate
  inheritance:
  - azure.mgmt.network.models.sub_resource.SubResource
  - msrest.serialization.Model
  - builtins.object
  module: azure.mgmt.network.models
  name: ApplicationGatewaySslCertificate
  source:
    id: ApplicationGatewaySslCertificate
    path: Users/eric/.virtualenvs/sphinx-docfx-yaml/lib/python3.5/site-packages/azure/mgmt/network/models/application_gateway_ssl_certificate.py
    remote:
      branch: master
      path: Users/eric/.virtualenvs/sphinx-docfx-yaml/lib/python3.5/site-packages/azure/mgmt/network/models/application_gateway_ssl_certificate.py
      repo: git@github.com:ericholscher/azure-sdk-for-python.git
    startLine: 15
  summary: "SSL certificates of application gateway.\n\n:param id: Resource Id\n:type\
    \ id: str\n:param data: SSL Certificate data\n:type data: str\n:param password:\
    \ SSL Certificate password\n:type password: str\n:param public_cert_data: SSL\
    \ Certificate public data\n:type public_cert_data: str\n:param provisioning_state:\
    \ Provisioning state of the ssl certificate\n resource Updating/Deleting/Failed\n\
    :type provisioning_state: str\n:param name: Name of the resource that is unique\
    \ within a resource group.\n This name can be used to access the resource\n:type\
    \ name: str\n:param etag: A unique read-only string that changes whenever the\
    \ resource\n is updated\n:type etag: str"
  type: Class
  uid: azure.mgmt.network.models.ApplicationGatewaySslCertificate
