api_name: []
items:
- _type: class
  children: []
  class: azure.mgmt.web.models.HostingEnvironmentDiagnostics
  fullName: azure.mgmt.web.models.HostingEnvironmentDiagnostics
  inheritance:
  - msrest.serialization.Model
  - builtins.object
  module: azure.mgmt.web.models
  name: HostingEnvironmentDiagnostics
  source:
    id: HostingEnvironmentDiagnostics
    path: azure-mgmt-web/azure/mgmt/web/models/hosting_environment_diagnostics.py
    remote:
      branch: master
      path: azure-mgmt-web/azure/mgmt/web/models/hosting_environment_diagnostics.py
      repo: https://github.com/Azure/azure-sdk-for-python/
    startLine: 15
  summary: 'Diagnostics for a hosting environment (App Service Environment).


    :param name: Name/identifier of the diagnostics

    :type name: str

    :param diagnosics_output: Diagnostics output

    :type diagnosics_output: str'
  type: Class
  uid: azure.mgmt.web.models.HostingEnvironmentDiagnostics
