api_name: []
items:
- _type: class
  children: []
  class: azure.mgmt.batch.models.AddApplicationParameters
  fullName: azure.mgmt.batch.models.AddApplicationParameters
  inheritance:
  - msrest.serialization.Model
  - builtins.object
  module: azure.mgmt.batch.models
  name: AddApplicationParameters
  source:
    id: AddApplicationParameters
    path: Users/eric/.virtualenvs/sphinx-docfx-yaml/lib/python3.5/site-packages/azure/mgmt/batch/models/add_application_parameters.py
    remote:
      branch: master
      path: Users/eric/.virtualenvs/sphinx-docfx-yaml/lib/python3.5/site-packages/azure/mgmt/batch/models/add_application_parameters.py
      repo: git@github.com:ericholscher/azure-sdk-for-python.git
    startLine: 15
  summary: "Parameters for an ApplicationOperations.AddApplication request.\n\n:param\
    \ allow_updates: A value indicating whether packages within the\n application\
    \ may be overwritten using the same version string.\n:type allow_updates: bool\n\
    :param display_name: The display name for the application.\n:type display_name:\
    \ str"
  type: Class
  uid: azure.mgmt.batch.models.AddApplicationParameters
