api_name: []
items:
- _type: class
  children: []
  class: azure.mgmt.network.models.ApplicationGatewayPaged
  fullName: azure.mgmt.network.models.ApplicationGatewayPaged
  inheritance:
  - msrest.paging.Paged
  - collections.abc.Iterator
  - collections.abc.Iterable
  - builtins.object
  module: azure.mgmt.network.models
  name: ApplicationGatewayPaged
  source:
    id: ApplicationGatewayPaged
    path: Users/eric/.virtualenvs/sphinx-docfx-yaml/lib/python3.5/site-packages/azure/mgmt/network/models/application_gateway_paged.py
    remote:
      branch: master
      path: Users/eric/.virtualenvs/sphinx-docfx-yaml/lib/python3.5/site-packages/azure/mgmt/network/models/application_gateway_paged.py
      repo: https://github.com/Azure/azure-sdk-for-python/
    startLine: 15
  summary: A paging container for iterating over a list of ApplicationGateway object
  type: Class
  uid: azure.mgmt.network.models.ApplicationGatewayPaged
