api_name: []
items:
- _type: class
  children: []
  class: azure.mgmt.web.models.FileSystemApplicationLogsConfig
  fullName: azure.mgmt.web.models.FileSystemApplicationLogsConfig
  inheritance:
  - msrest.serialization.Model
  - builtins.object
  module: azure.mgmt.web.models
  name: FileSystemApplicationLogsConfig
  source:
    id: FileSystemApplicationLogsConfig
    path: azure-mgmt-web/azure/mgmt/web/models/file_system_application_logs_config.py
    remote:
      branch: master
      path: azure-mgmt-web/azure/mgmt/web/models/file_system_application_logs_config.py
      repo: git@github.com:ericholscher/azure-sdk-for-python.git
    startLine: 15
  summary: "Application logs to file system configuration.\n\n:param level: Log level.\
    \ Possible values include: 'Off', 'Verbose',\n 'Information', 'Warning', 'Error'.\
    \ Default value: \"Off\" .\n:type level: str or :class:`LogLevel <azure.mgmt.web.models.LogLevel>`"
  type: Class
  uid: azure.mgmt.web.models.FileSystemApplicationLogsConfig
