api_name: []
items:
- _type: class
  children: []
  class: azure.mgmt.datalake.store.models.EncryptionConfig
  fullName: azure.mgmt.datalake.store.models.EncryptionConfig
  inheritance:
  - msrest.serialization.Model
  - builtins.object
  module: azure.mgmt.datalake.store.models
  name: EncryptionConfig
  source:
    id: EncryptionConfig
    path: azure-mgmt-datalake-store/azure/mgmt/datalake/store/models/encryption_config.py
    remote:
      branch: master
      path: azure-mgmt-datalake-store/azure/mgmt/datalake/store/models/encryption_config.py
      repo: https://github.com/Azure/azure-sdk-for-python/
    startLine: 15
  summary: "The encryption configuration for the account.\n\n:param type: The type\
    \ of encryption configuration being used. Currently\n the only supported types\
    \ are 'UserManaged' and 'ServiceManaged'. Possible\n values include: 'UserManaged',\
    \ 'ServiceManaged'\n:type type: str or :class:`EncryptionConfigType\n <azure.mgmt.datalake.store.models.EncryptionConfigType>`\n\
    :param key_vault_meta_info: The Key vault information for connecting to\n user\
    \ managed encryption keys.\n:type key_vault_meta_info: :class:`KeyVaultMetaInfo\n\
    \ <azure.mgmt.datalake.store.models.KeyVaultMetaInfo>`"
  type: Class
  uid: azure.mgmt.datalake.store.models.EncryptionConfig
