api_name: []
items:
- _type: class
  children: []
  class: azure.mgmt.web.models.AzureBlobStorageHttpLogsConfig
  fullName: azure.mgmt.web.models.AzureBlobStorageHttpLogsConfig
  inheritance:
  - msrest.serialization.Model
  - builtins.object
  module: azure.mgmt.web.models
  name: AzureBlobStorageHttpLogsConfig
  source:
    id: AzureBlobStorageHttpLogsConfig
    path: azure-mgmt-web/azure/mgmt/web/models/azure_blob_storage_http_logs_config.py
    remote:
      branch: master
      path: azure-mgmt-web/azure/mgmt/web/models/azure_blob_storage_http_logs_config.py
      repo: git@github.com:ericholscher/azure-sdk-for-python.git
    startLine: 15
  summary: "Http logs to azure blob storage configuration.\n\n:param sas_url: SAS\
    \ url to a azure blob container with\n read/write/list/delete permissions.\n:type\
    \ sas_url: str\n:param retention_in_days: Retention in days.\n Remove blobs older\
    \ than X days.\n 0 or lower means no retention.\n:type retention_in_days: int\n\
    :param enabled: Enabled.\n:type enabled: bool"
  type: Class
  uid: azure.mgmt.web.models.AzureBlobStorageHttpLogsConfig
