api_name: []
items:
- _type: class
  children: []
  class: azure.servicemanagement.models.ConfigurationSetInputEndpoint
  fullName: azure.servicemanagement.models.ConfigurationSetInputEndpoint
  inheritance:
  - azure.servicemanagement._common_models.WindowsAzureData
  - builtins.object
  module: azure.servicemanagement.models
  name: ConfigurationSetInputEndpoint
  source:
    id: ConfigurationSetInputEndpoint
    path: Users/eric/.virtualenvs/sphinx-docfx-yaml/lib/python3.5/site-packages/azure/servicemanagement/models.py
    remote:
      branch: master
      path: Users/eric/.virtualenvs/sphinx-docfx-yaml/lib/python3.5/site-packages/azure/servicemanagement/models.py
      repo: https://github.com/Azure/azure-sdk-for-python/
    startLine: 1162
  summary: "Initializes a network configuration input endpoint.\n\nname:\n    Specifies\
    \ the name for the external endpoint.\nprotocol:\n    Specifies the protocol to\
    \ use to inspect the virtual machine\n    availability status. Possible values\
    \ are: HTTP, TCP.\nport:\n    Specifies the external port to use for the endpoint.\n\
    local_port:\n    Specifies the internal port on which the virtual machine is listening\n\
    \    to serve the endpoint.\nload_balanced_endpoint_set_name:\n    Specifies a\
    \ name for a set of load-balanced endpoints. Specifying this\n    element for\
    \ a given endpoint adds it to the set. If you are setting an\n    endpoint to\
    \ use to connect to the virtual machine via the Remote\n    Desktop, do not set\
    \ this property.\nenable_direct_server_return:\n    Specifies whether direct server\
    \ return load balancing is enabled."
  type: Class
  uid: azure.servicemanagement.models.ConfigurationSetInputEndpoint
