api_name: []
items:
- _type: class
  children: []
  class: azure.batch.models.ComputeNodeGetRemoteLoginSettingsResult
  fullName: azure.batch.models.ComputeNodeGetRemoteLoginSettingsResult
  inheritance:
  - msrest.serialization.Model
  - builtins.object
  module: azure.batch.models
  name: ComputeNodeGetRemoteLoginSettingsResult
  source:
    id: ComputeNodeGetRemoteLoginSettingsResult
    path: Users/eric/.virtualenvs/sphinx-docfx-yaml/lib/python3.5/site-packages/azure/batch/models/compute_node_get_remote_login_settings_result.py
    remote:
      branch: master
      path: Users/eric/.virtualenvs/sphinx-docfx-yaml/lib/python3.5/site-packages/azure/batch/models/compute_node_get_remote_login_settings_result.py
      repo: https://github.com/Azure/azure-sdk-for-python/
    startLine: 15
  summary: "Response to a ComputeNodeOperation.GetRemoteLoginSettings request.\n\n\
    :param remote_login_ip_address: The IP address used for remote login to\n the\
    \ compute node.\n:type remote_login_ip_address: str\n:param remote_login_port:\
    \ The port used for remote login to the compute\n node.\n:type remote_login_port:\
    \ int"
  type: Class
  uid: azure.batch.models.ComputeNodeGetRemoteLoginSettingsResult
