api_name: []
items:
- _type: class
  children: []
  class: azure.mgmt.web.models.SlotConfigNames
  fullName: azure.mgmt.web.models.SlotConfigNames
  inheritance:
  - msrest.serialization.Model
  - builtins.object
  module: azure.mgmt.web.models
  name: SlotConfigNames
  source:
    id: SlotConfigNames
    path: azure-mgmt-web/azure/mgmt/web/models/slot_config_names.py
    remote:
      branch: master
      path: azure-mgmt-web/azure/mgmt/web/models/slot_config_names.py
      repo: https://github.com/Azure/azure-sdk-for-python/
    startLine: 15
  summary: 'Class containing names for connection strings and application settings
    to

    be marked as sticky to the slot

    and not moved during swap operation

    This is valid for all deployment slots under the site.


    :param connection_string_names: List of connection string names

    :type connection_string_names: list of str

    :param app_setting_names: List of application settings names

    :type app_setting_names: list of str'
  type: Class
  uid: azure.mgmt.web.models.SlotConfigNames
