api_name: []
items:
- _type: class
  children: []
  class: azure.mgmt.web.models.HostingEnvironmentStatus
  fullName: azure.mgmt.web.models.HostingEnvironmentStatus
  inheritance:
  - enum.Enum
  - builtins.object
  module: azure.mgmt.web.models
  name: HostingEnvironmentStatus
  source:
    id: HostingEnvironmentStatus
    path: azure-mgmt-web/azure/mgmt/web/models/web_site_management_client_enums.py
    remote:
      branch: master
      path: azure-mgmt-web/azure/mgmt/web/models/web_site_management_client_enums.py
      repo: https://github.com/Azure/azure-sdk-for-python/
    startLine: 185
  summary: An enumeration.
  type: Class
  uid: azure.mgmt.web.models.HostingEnvironmentStatus
