api_name: []
items:
- _type: class
  children: []
  class: azure.batch.models.ApplicationSummaryPaged
  fullName: azure.batch.models.ApplicationSummaryPaged
  inheritance:
  - msrest.paging.Paged
  - collections.abc.Iterator
  - collections.abc.Iterable
  - builtins.object
  module: azure.batch.models
  name: ApplicationSummaryPaged
  source:
    id: ApplicationSummaryPaged
    path: Users/eric/.virtualenvs/sphinx-docfx-yaml/lib/python3.5/site-packages/azure/batch/models/application_summary_paged.py
    remote:
      branch: master
      path: Users/eric/.virtualenvs/sphinx-docfx-yaml/lib/python3.5/site-packages/azure/batch/models/application_summary_paged.py
      repo: https://github.com/Azure/azure-sdk-for-python/
    startLine: 15
  summary: A paging container for iterating over a list of ApplicationSummary object
  type: Class
  uid: azure.batch.models.ApplicationSummaryPaged
