api_name: []
items:
- _type: class
  children: []
  class: azure.mgmt.batch.models.UpdateApplicationParameters
  fullName: azure.mgmt.batch.models.UpdateApplicationParameters
  inheritance:
  - msrest.serialization.Model
  - builtins.object
  module: azure.mgmt.batch.models
  name: UpdateApplicationParameters
  source:
    id: UpdateApplicationParameters
    path: Users/eric/.virtualenvs/sphinx-docfx-yaml/lib/python3.5/site-packages/azure/mgmt/batch/models/update_application_parameters.py
    remote:
      branch: master
      path: Users/eric/.virtualenvs/sphinx-docfx-yaml/lib/python3.5/site-packages/azure/mgmt/batch/models/update_application_parameters.py
      repo: https://github.com/Azure/azure-sdk-for-python/
    startLine: 15
  summary: "Parameters for an ApplicationOperations.UpdateApplication request.\n\n\
    :param allow_updates: A value indicating whether packages within the\n application\
    \ may be overwritten using the same version string.\n:type allow_updates: bool\n\
    :param default_version: The package to use if a client requests the\n application\
    \ but does not specify a version.\n:type default_version: str\n:param display_name:\
    \ The display name for the application.\n:type display_name: str"
  type: Class
  uid: azure.mgmt.batch.models.UpdateApplicationParameters
