api_name: []
items:
- _type: class
  children: []
  class: azure.mgmt.logic.models.AS2ErrorSettings
  fullName: azure.mgmt.logic.models.AS2ErrorSettings
  inheritance:
  - msrest.serialization.Model
  - builtins.object
  module: azure.mgmt.logic.models
  name: AS2ErrorSettings
  source:
    id: AS2ErrorSettings
    path: Users/eric/.virtualenvs/sphinx-docfx-yaml/lib/python3.5/site-packages/azure/mgmt/logic/models/as2_error_settings.py
    remote:
      branch: master
      path: Users/eric/.virtualenvs/sphinx-docfx-yaml/lib/python3.5/site-packages/azure/mgmt/logic/models/as2_error_settings.py
      repo: git@github.com:ericholscher/azure-sdk-for-python.git
    startLine: 15
  summary: "AS2ErrorSettings.\n\n:param suspend_duplicate_message: The value indicating\
    \ whether to suspend\n duplicate message.\n:type suspend_duplicate_message: bool\n\
    :param resend_if_mdn_not_received: The value indicating whether to resend\n message\
    \ If MDN is not received.\n:type resend_if_mdn_not_received: bool"
  type: Class
  uid: azure.mgmt.logic.models.AS2ErrorSettings
