api_name: []
items:
- _type: class
  children:
  - azure.mgmt.monitor.operations.AutoscaleSettingsOperations.create_or_update
  - azure.mgmt.monitor.operations.AutoscaleSettingsOperations.delete
  - azure.mgmt.monitor.operations.AutoscaleSettingsOperations.get
  - azure.mgmt.monitor.operations.AutoscaleSettingsOperations.list_by_resource_group
  class: azure.mgmt.monitor.operations.AutoscaleSettingsOperations
  fullName: azure.mgmt.monitor.operations.AutoscaleSettingsOperations
  inheritance:
  - builtins.object
  module: azure.mgmt.monitor.operations
  name: AutoscaleSettingsOperations
  source:
    id: AutoscaleSettingsOperations
    path: azure-mgmt-monitor/azure/mgmt/monitor/operations/autoscale_settings_operations.py
    remote:
      branch: master
      path: azure-mgmt-monitor/azure/mgmt/monitor/operations/autoscale_settings_operations.py
      repo: https://github.com/Azure/azure-sdk-for-python/
    startLine: 19
  summary: 'AutoscaleSettingsOperations operations.


    :param client: Client for service requests.

    :param config: Configuration of service client.

    :param serializer: An object model serializer.

    :param deserializer: An objec model deserializer.

    :ivar api_version: Client Api Version. Constant value: "2015-04-01".'
  type: Class
  uid: azure.mgmt.monitor.operations.AutoscaleSettingsOperations
- _type: method
  class: azure.mgmt.monitor.operations.AutoscaleSettingsOperations
  fullName: azure.mgmt.monitor.operations.AutoscaleSettingsOperations.create_or_update
  module: azure.mgmt.monitor.operations
  name: create_or_update
  source:
    id: create_or_update
    path: azure-mgmt-monitor/azure/mgmt/monitor/operations/autoscale_settings_operations.py
    remote:
      branch: master
      path: azure-mgmt-monitor/azure/mgmt/monitor/operations/autoscale_settings_operations.py
      repo: https://github.com/Azure/azure-sdk-for-python/
    startLine: 110
  summary: "Creates or updates an autoscale setting.\n\n:param resource_group_name:\
    \ The name of the resource group.\n:type resource_group_name: str\n:param autoscale_setting_name:\
    \ The autoscale setting name.\n:type autoscale_setting_name: str\n:param parameters:\
    \ Parameters supplied to the operation.\n:type parameters: :class:`AutoscaleSettingResource\n\
    \ <azure.mgmt.monitor.models.AutoscaleSettingResource>`\n:param dict custom_headers:\
    \ headers that will be added to the request\n:param bool raw: returns the direct\
    \ response alongside the\n deserialized response\n:param operation_config: :ref:`Operation\
    \ configuration\n overrides<msrest:optionsforoperations>`.\n:rtype: :class:`AutoscaleSettingResource\n\
    \ <azure.mgmt.monitor.models.AutoscaleSettingResource>`\n:rtype: :class:`ClientRawResponse<msrest.pipeline.ClientRawResponse>`\n\
    \ if raw=true\n:raises: :class:`CloudError<msrestazure.azure_exceptions.CloudError>`"
  type: Method
  uid: azure.mgmt.monitor.operations.AutoscaleSettingsOperations.create_or_update
- _type: method
  class: azure.mgmt.monitor.operations.AutoscaleSettingsOperations
  fullName: azure.mgmt.monitor.operations.AutoscaleSettingsOperations.delete
  module: azure.mgmt.monitor.operations
  name: delete
  source:
    id: delete
    path: azure-mgmt-monitor/azure/mgmt/monitor/operations/autoscale_settings_operations.py
    remote:
      branch: master
      path: azure-mgmt-monitor/azure/mgmt/monitor/operations/autoscale_settings_operations.py
      repo: https://github.com/Azure/azure-sdk-for-python/
    startLine: 181
  summary: "Deletes and autoscale setting.\n\n:param resource_group_name: The name\
    \ of the resource group.\n:type resource_group_name: str\n:param autoscale_setting_name:\
    \ The autoscale setting name.\n:type autoscale_setting_name: str\n:param dict\
    \ custom_headers: headers that will be added to the request\n:param bool raw:\
    \ returns the direct response alongside the\n deserialized response\n:param operation_config:\
    \ :ref:`Operation configuration\n overrides<msrest:optionsforoperations>`.\n:rtype:\
    \ None\n:rtype: :class:`ClientRawResponse<msrest.pipeline.ClientRawResponse>`\n\
    \ if raw=true\n:raises: :class:`CloudError<msrestazure.azure_exceptions.CloudError>`"
  type: Method
  uid: azure.mgmt.monitor.operations.AutoscaleSettingsOperations.delete
- _type: method
  class: azure.mgmt.monitor.operations.AutoscaleSettingsOperations
  fullName: azure.mgmt.monitor.operations.AutoscaleSettingsOperations.get
  module: azure.mgmt.monitor.operations
  name: get
  source:
    id: get
    path: azure-mgmt-monitor/azure/mgmt/monitor/operations/autoscale_settings_operations.py
    remote:
      branch: master
      path: azure-mgmt-monitor/azure/mgmt/monitor/operations/autoscale_settings_operations.py
      repo: https://github.com/Azure/azure-sdk-for-python/
    startLine: 235
  summary: "Gets an autoscale setting.\n\n:param resource_group_name: The name of\
    \ the resource group.\n:type resource_group_name: str\n:param autoscale_setting_name:\
    \ The autoscale setting name.\n:type autoscale_setting_name: str\n:param dict\
    \ custom_headers: headers that will be added to the request\n:param bool raw:\
    \ returns the direct response alongside the\n deserialized response\n:param operation_config:\
    \ :ref:`Operation configuration\n overrides<msrest:optionsforoperations>`.\n:rtype:\
    \ :class:`AutoscaleSettingResource\n <azure.mgmt.monitor.models.AutoscaleSettingResource>`\n\
    :rtype: :class:`ClientRawResponse<msrest.pipeline.ClientRawResponse>`\n if raw=true\n\
    :raises: :class:`CloudError<msrestazure.azure_exceptions.CloudError>`"
  type: Method
  uid: azure.mgmt.monitor.operations.AutoscaleSettingsOperations.get
- _type: method
  class: azure.mgmt.monitor.operations.AutoscaleSettingsOperations
  fullName: azure.mgmt.monitor.operations.AutoscaleSettingsOperations.list_by_resource_group
  module: azure.mgmt.monitor.operations
  name: list_by_resource_group
  source:
    id: list_by_resource_group
    path: azure-mgmt-monitor/azure/mgmt/monitor/operations/autoscale_settings_operations.py
    remote:
      branch: master
      path: azure-mgmt-monitor/azure/mgmt/monitor/operations/autoscale_settings_operations.py
      repo: https://github.com/Azure/azure-sdk-for-python/
    startLine: 38
  summary: "Lists the autoscale settings for a resource group.\n\n:param resource_group_name:\
    \ The name of the resource group.\n:type resource_group_name: str\n:param filter:\
    \ The filter to apply on the operation. For more\n information please see\n https://msdn.microsoft.com/en-us/library/azure/dn931934.aspx\n\
    :type filter: str\n:param dict custom_headers: headers that will be added to the\
    \ request\n:param bool raw: returns the direct response alongside the\n deserialized\
    \ response\n:param operation_config: :ref:`Operation configuration\n overrides<msrest:optionsforoperations>`.\n\
    :rtype: :class:`AutoscaleSettingResourcePaged\n <azure.mgmt.monitor.models.AutoscaleSettingResourcePaged>`\n\
    :raises: :class:`CloudError<msrestazure.azure_exceptions.CloudError>`"
  type: Method
  uid: azure.mgmt.monitor.operations.AutoscaleSettingsOperations.list_by_resource_group
