api_name: []
items:
- _type: class
  children: []
  class: azure.mgmt.web.models.HostingEnvironmentProfile
  fullName: azure.mgmt.web.models.HostingEnvironmentProfile
  inheritance:
  - msrest.serialization.Model
  - builtins.object
  module: azure.mgmt.web.models
  name: HostingEnvironmentProfile
  source:
    id: HostingEnvironmentProfile
    path: azure-mgmt-web/azure/mgmt/web/models/hosting_environment_profile.py
    remote:
      branch: master
      path: azure-mgmt-web/azure/mgmt/web/models/hosting_environment_profile.py
      repo: git@github.com:ericholscher/azure-sdk-for-python.git
    startLine: 15
  summary: 'Specification for an App Service Environment to use for this resource.


    Variables are only populated by the server, and will be ignored when

    sending a request.


    :param id: Resource ID of the App Service Environment.

    :type id: str

    :ivar name: Name of the App Service Environment.

    :vartype name: str

    :ivar type: Resource type of the App Service Environment.

    :vartype type: str'
  type: Class
  uid: azure.mgmt.web.models.HostingEnvironmentProfile
