api_name: []
items:
- _type: class
  children: []
  class: azure.mgmt.web.models.SiteAuthSettings
  fullName: azure.mgmt.web.models.SiteAuthSettings
  inheritance:
  - msrest.serialization.Model
  - builtins.object
  module: azure.mgmt.web.models
  name: SiteAuthSettings
  source:
    id: SiteAuthSettings
    path: azure-mgmt-web/azure/mgmt/web/models/site_auth_settings.py
    remote:
      branch: master
      path: azure-mgmt-web/azure/mgmt/web/models/site_auth_settings.py
      repo: git@github.com:ericholscher/azure-sdk-for-python.git
    startLine: 15
  summary: "Configuration settings for the Azure App Service Authentication /\nAuthorization\
    \ feature.\n\n:param enabled: <code>true</code> if the Authentication / Authorization\n\
    \ feature is enabled for the current app; otherwise, <code>false</code>.\n:type\
    \ enabled: bool\n:param runtime_version: The RuntimeVersion of the Authentication\
    \ /\n Authorization feature in use for the current app.\n The setting in this\
    \ value can control the behavior of certain features in\n the Authentication /\
    \ Authorization module.\n:type runtime_version: str\n:param unauthenticated_client_action:\
    \ The action to take when an\n unauthenticated client attempts to access the app.\
    \ Possible values\n include: 'RedirectToLoginPage', 'AllowAnonymous'\n:type unauthenticated_client_action:\
    \ str or\n :class:`UnauthenticatedClientAction\n <azure.mgmt.web.models.UnauthenticatedClientAction>`\n\
    :param token_store_enabled: <code>true</code> to durably store\n platform-specific\
    \ security tokens that are obtained during login flows;\n otherwise, <code>false</code>.\n\
    \ The default is <code>false</code>.\n:type token_store_enabled: bool\n:param\
    \ allowed_external_redirect_urls: External URLs that can be\n redirected to as\
    \ part of logging in or logging out of the app. Note that\n the query string part\
    \ of the URL is ignored.\n This is an advanced setting typically only needed by\
    \ Windows Store\n application backends.\n Note that URLs within the current domain\
    \ are always implicitly allowed.\n:type allowed_external_redirect_urls: list of\
    \ str\n:param default_provider: The default authentication provider to use when\n\
    \ multiple providers are configured.\n This setting is only needed if multiple\
    \ providers are configured and the\n unauthenticated client\n action is set to\
    \ \"RedirectToLoginPage\". Possible values include:\n 'AzureActiveDirectory',\
    \ 'Facebook', 'Google', 'MicrosoftAccount',\n 'Twitter'\n:type default_provider:\
    \ str or :class:`BuiltInAuthenticationProvider\n <azure.mgmt.web.models.BuiltInAuthenticationProvider>`\n\
    :param token_refresh_extension_hours: The number of hours after session\n token\
    \ expiration that a session token can be used to\n call the token refresh API.\
    \ The default is 72 hours.\n:type token_refresh_extension_hours: float\n:param\
    \ client_id: The Client ID of this relying party application, known\n as the client_id.\n\
    \ This setting is required for enabling OpenID Connection authentication\n with\
    \ Azure Active Directory or\n other 3rd party OpenID Connect providers.\n More\
    \ information on OpenID Connect:\n http://openid.net/specs/openid-connect-core-1_0.html\n\
    :type client_id: str\n:param client_secret: The Client Secret of this relying\
    \ party application\n (in Azure Active Directory, this is also referred to as\
    \ the Key).\n This setting is optional. If no client secret is configured, the\
    \ OpenID\n Connect implicit auth flow is used to authenticate end users.\n Otherwise,\
    \ the OpenID Connect Authorization Code Flow is used to\n authenticate end users.\n\
    \ More information on OpenID Connect:\n http://openid.net/specs/openid-connect-core-1_0.html\n\
    :type client_secret: str\n:param issuer: The OpenID Connect Issuer URI that represents\
    \ the entity\n which issues access tokens for this application.\n When using Azure\
    \ Active Directory, this value is the URI of the directory\n tenant, e.g. https://sts.windows.net/{tenant-guid}/.\n\
    \ This URI is a case-sensitive identifier for the token issuer.\n More information\
    \ on OpenID Connect Discovery:\n http://openid.net/specs/openid-connect-discovery-1_0.html\n\
    :type issuer: str\n:param allowed_audiences: Allowed audience values to consider\
    \ when\n validating JWTs issued by\n Azure Active Directory. Note that the <code>ClientID</code>\
    \ value is\n always considered an\n allowed audience, regardless of this setting.\n\
    :type allowed_audiences: list of str\n:param additional_login_params: Login parameters\
    \ to send to the OpenID\n Connect authorization endpoint when\n a user logs in.\
    \ Each parameter must be in the form \"key=value\".\n:type additional_login_params:\
    \ list of str\n:param google_client_id: The OpenID Connect Client ID for the Google\
    \ web\n application.\n This setting is required for enabling Google Sign-In.\n\
    \ Google Sign-In documentation:\n https://developers.google.com/identity/sign-in/web/\n\
    :type google_client_id: str\n:param google_client_secret: The client secret associated\
    \ with the Google\n web application.\n This setting is required for enabling Google\
    \ Sign-In.\n Google Sign-In documentation:\n https://developers.google.com/identity/sign-in/web/\n\
    :type google_client_secret: str\n:param google_oauth_scopes: The OAuth 2.0 scopes\
    \ that will be requested as\n part of Google Sign-In authentication.\n This setting\
    \ is optional. If not specified, \"openid\", \"profile\", and\n \"email\" are\
    \ used as default scopes.\n Google Sign-In documentation:\n https://developers.google.com/identity/sign-in/web/\n\
    :type google_oauth_scopes: list of str\n:param facebook_app_id: The App ID of\
    \ the Facebook app used for login.\n This setting is required for enabling Facebook\
    \ Login.\n Facebook Login documentation:\n https://developers.facebook.com/docs/facebook-login\n\
    :type facebook_app_id: str\n:param facebook_app_secret: The App Secret of the\
    \ Facebook app used for\n Facebook Login.\n This setting is required for enabling\
    \ Facebook Login.\n Facebook Login documentation:\n https://developers.facebook.com/docs/facebook-login\n\
    :type facebook_app_secret: str\n:param facebook_oauth_scopes: The OAuth 2.0 scopes\
    \ that will be requested\n as part of Facebook Login authentication.\n This setting\
    \ is optional.\n Facebook Login documentation:\n https://developers.facebook.com/docs/facebook-login\n\
    :type facebook_oauth_scopes: list of str\n:param twitter_consumer_key: The OAuth\
    \ 1.0a consumer key of the Twitter\n application used for sign-in.\n This setting\
    \ is required for enabling Twitter Sign-In.\n Twitter Sign-In documentation: https://dev.twitter.com/web/sign-in\n\
    :type twitter_consumer_key: str\n:param twitter_consumer_secret: The OAuth 1.0a\
    \ consumer secret of the\n Twitter application used for sign-in.\n This setting\
    \ is required for enabling Twitter Sign-In.\n Twitter Sign-In documentation: https://dev.twitter.com/web/sign-in\n\
    :type twitter_consumer_secret: str\n:param microsoft_account_client_id: The OAuth\
    \ 2.0 client ID that was\n created for the app used for authentication.\n This\
    \ setting is required for enabling Microsoft Account authentication.\n Microsoft\
    \ Account OAuth documentation:\n https://dev.onedrive.com/auth/msa_oauth.htm\n\
    :type microsoft_account_client_id: str\n:param microsoft_account_client_secret:\
    \ The OAuth 2.0 client secret that\n was created for the app used for authentication.\n\
    \ This setting is required for enabling Microsoft Account authentication.\n Microsoft\
    \ Account OAuth documentation:\n https://dev.onedrive.com/auth/msa_oauth.htm\n\
    :type microsoft_account_client_secret: str\n:param microsoft_account_oauth_scopes:\
    \ The OAuth 2.0 scopes that will be\n requested as part of Microsoft Account authentication.\n\
    \ This setting is optional. If not specified, \"wl.basic\" is used as the\n default\
    \ scope.\n Microsoft Account Scopes and permissions documentation:\n https://msdn.microsoft.com/en-us/library/dn631845.aspx\n\
    :type microsoft_account_oauth_scopes: list of str"
  type: Class
  uid: azure.mgmt.web.models.SiteAuthSettings
