api_name: []
items:
- _type: class
  children: []
  class: azure.batch.models.ApplicationPackageReference
  fullName: azure.batch.models.ApplicationPackageReference
  inheritance:
  - msrest.serialization.Model
  - builtins.object
  module: azure.batch.models
  name: ApplicationPackageReference
  source:
    id: ApplicationPackageReference
    path: Users/eric/.virtualenvs/sphinx-docfx-yaml/lib/python3.5/site-packages/azure/batch/models/application_package_reference.py
    remote:
      branch: master
      path: Users/eric/.virtualenvs/sphinx-docfx-yaml/lib/python3.5/site-packages/azure/batch/models/application_package_reference.py
      repo: https://github.com/Azure/azure-sdk-for-python/
    startLine: 15
  summary: "A reference to an application package to be deployed to compute nodes.\n\
    \n:param application_id: The id of the application to deploy.\n:type application_id:\
    \ str\n:param version: The version of the application to deploy. If omitted, the\n\
    \ default version is deployed.\n:type version: str"
  type: Class
  uid: azure.batch.models.ApplicationPackageReference
